version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"

  # --- APPS ---

  - package-ecosystem: "npm"
    directory: "/app/app"
    schedule:
      interval: "weekly"
      day: "saturday"

  # --- PACKAGES ---

  - package-ecosystem: "npm"
    directory: "/package/all"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/package/api"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/package/component"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/package/logging"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/package/sheet-logic"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/package/state"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/package/type"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/package/util"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/package/window-upload"
    schedule:
      interval: "weekly"
      day: "saturday"
