version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/app/gm-screen"
    schedule:
      interval: "weekly"
      day: "saturday"

  - package-ecosystem: "npm"
    directory: "/package/all"
    schedule:
      interval: "weekly"
      day: "saturday"
