import { useReducer } from "react";
import { v4 as uuid } from "uuid";
import { SheetState, sheetStateReducer } from "type/sheet";
import { Sheet } from "component/Sheet";

const collectionInitialState: SheetState = {
  id: "",
  name: "",
  groups: [],
  items: [
    {
      id: uuid(),
      type: "omni",
      group: "",
      key: "str",
      name: "Strength",
      value: "12",
      readOnly: false,
      onclickEnabled: false,
      onclick: "",
    },
    {
      id: uuid(),
      type: "omni",
      group: "",
      key: "con",
      name: "Constitution",
      value: "13",
      readOnly: false,
      onclickEnabled: false,
      onclick: "",
    },
    {
      id: uuid(),
      type: "range",
      group: "",
      key: "hp",
      name: "HP",
      value: "22",
      readOnly: false,
      onclickEnabled: false,
      onclick: "",
      min: "0",
      max: "={{level}} * (ceil(({{hit_die}} + 1) / 2) + {{con_mod}})",
    },
    {
      id: uuid(),
      type: "omni",
      group: "",
      key: "prof",
      name: "Proficiency Bonus",
      value: "3",
      readOnly: false,
      onclickEnabled: true,
      onclick: "=d20 + {{self}}",
    },
    {
      id: uuid(),
      type: "omni",
      group: "",
      key: "str_mod",
      name: "Strength Modifier",
      value: "=floor(({{str}}-10)/2)",
      readOnly: true,
      onclickEnabled: true,
      onclick: "=d20 + {{self}} + {{prof}}",
    },
    {
      id: uuid(),
      type: "range",
      group: "",
      key: "level",
      name: "Level",
      value: "3",
      min: "1",
      max: "20",
      readOnly: false,
      onclickEnabled: false,
      onclick: "",
    },
    {
      id: uuid(),
      type: "omni",
      group: "",
      key: "hit_die",
      name: "Hit Die",
      value: "10",
      readOnly: false,
      onclickEnabled: true,
      onclick: "=d{{self}} + {{prof}}",
    },
    {
      id: uuid(),
      type: "omni",
      group: "",
      key: "con_mod",
      name: "Constitution Modifier",
      value: "=floor(({{con}}-10)/2)",
      readOnly: true,
      onclickEnabled: true,
      onclick: "=d20 + {{self}} + {{prof}}",
    },
    {
      id: uuid(),
      type: "boolean",
      group: "",
      key: "athletics",
      name: "Athletics",
      value: "0",
      readOnly: false,
      onclickEnabled: true,
      onclick: "=d20 + {{str_mod}} + {{self}} * {{prof}}",
    },
  ],
};

export default function Space(): React.ReactNode {
  const [state, dispatch] = useReducer(sheetStateReducer, collectionInitialState);
  return <Sheet {...{ state, dispatch }} />;
}
