name: check

on: [push]

jobs:
  check:
    name: Run checks and tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: make init

      - name: Run all checks and tests
        run: make -j check test-jest

      - name: Build next app
        run: npm run --workspaces --if-present build
